#!/bin/zsh

# Add commonly used folders to $PATH
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Export Rust as installed through Rustup
export PATH="$HOME/.cargo/bin:$PATH"

# Specify default editor.
export EDITOR=nano

# Create a folder and move into it in one command
function mkcd() { mkdir -p "$@" && cd "$_"; }
