[tools]
act = "latest"
actionlint = "latest"
age = "latest"
"aqua:walles/moor" = "latest"
bat = "latest"
buf = "latest"
bun = "latest"
delta = "latest"
dive = "latest"
doggo = "latest"
dotnet = "latest"
duckdb = "latest"
eza = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
go = "latest"
gping = "latest"
gradle = "latest"
grpcurl = "latest"
hadolint = "latest"
helm = "latest"
hk = "latest"
hurl = "latest"
java = "latest"
jq = "latest"
krew = "latest"
kubecolor = "latest"
kubectl = "latest"
kubelogin = "latest"
kustomize = "latest"
maven = "latest"
node = "latest"
oxfmt = "latest"
pkl = "latest"
pnpm = "latest"
powershell = "latest"
protoc = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
sops = "latest"
talosctl = "latest"
uv = "latest"
yq = "latest"
zizmor = "latest"
zoxide = "latest"

[settings.ruby]
# Error out during install if precompiled Ruby is not available from github.com/jdx/ruby
compile = false
